### PR TITLE
Update recipe to match upstream deps

### PR DESCRIPTION
**Pull request by hajapy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hajapy** [comment]
@conda-forge-admin, please rerender

**Comment by hajapy** [comment]
@conda-forge-admin, please lint

**Comment by hajapy** [comment]
@conda-forge-admin, please rerender

**Comment by hajapy** [comment]
https://github.com/sffjunkie/astral/blob/master/ChangeLog.md#30-2022-10-07

Upstream switched from pytz to stdlib zoneinfo or backports.zoneinfo for py < 3.9. I think this means the recipe should lose  noarch status, but I had problems setting that up (linter complaining). 

As is, keeping noarch I think will produce a package where astral won't be installable under py310 due to lack of backports.zoneinfo being built for py310, so I'm not sure it's a good idea to merge.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
