### PR TITLE
Attempting to fix recipe for latest version

### PR DESCRIPTION
**Pull request by jbusecke**
Towards closing #10 

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jbusecke** [comment]
@conda-forge-admin please rerender

**Comment by jbusecke** [comment]
Is there any interest in this PR? Otherwise I can close it, since we decided to go another route in the downstream package.

@mariusvniekerk @beckermr @hajapy

**Comment by beckermr** [comment]
If you'd like to be a maintainer, feel free to add your name in the recipe and we can merge.

**Comment by jbusecke** [comment]
Thanks for the offer, but I will have to decline. I don't think I know enough about the package, and am committed quite highly in other efforts for the foreseeable future. This was mainly an attempt to fix the aforementioned downstream issue. 
I'll close this then.

**Pull request closed without merging**
